services:
  mongo:
    image: mongo:8
    container_name: {MONGO_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "{MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
      - ./rsc/init.js:/docker-entrypoint-initdb.d/init.js:ro

volumes:
  mongo_data:
